### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by giggio** [csmacnz/coveralls.net#2]
I can see that OpenCover support is not finished, but there is no backlog, so I am not sure what is missing. I see your reports on https://coveralls.io/r/csmacnz/coveralls.net, so it looks good. What is missing?
Also, why is the package unlisted on nuget?
https://www.nuget.org/packages/coveralls.net

**Comment by csmacnz** [comment]
Hey @giggio, thanks for your interest in my tool.  Yeah so this has been dragging on a bit for me, but also I've had a busy few months to find the time to add the last few things for MVP, ill add some items to my backlog so you can get better visibility on progress.

At this stage I still have to remove a bunch of hard-coded appveyor environment variables so that these can be passed in as parameters, and suss out how I will pull in the git details, whether through parameters, environment variables or expecting git to be available at the command line (maybe all three?) at a minimum I don't want it to be hard-coded to appveyor.

I also need to look into coverage around auto-properties, since this is not directly connected to a source file line, but I know [ReportGenerator](https://reportgenerator.codeplex.com/) support this, so should be able to glean how to do this.  This probably isn't mvp, just a thing to sort out.

Finally, I barely got the nuget package generation cobbled together the other week, so it needs tested before I'm happy to publish it that it works as expected.

If you would like to start using this in your project I'd be more than happy to work with you to make this happen, and if you don't mind a few issues along the way I can look at getting something viable on nuget sooner?  (its still v0.1 so people will expect bugs right? :) )
