### ISSUE TITLE
coveralls.net sometimes fails with "Usage" message

### ISSUE THREAD

**Issue by csoltenborn** [csMACnz/coveralls.net#53]
We're using coveralls.net to upload our OpenCover coverage data to Coveralls via an AppVeyor build. However, sometimes this fails for reasons I do not understand. For instance, currently it does not work (most of the time, it worked "the next day", but it now consistently failed for a couple of days already). Here's some output of our AppVeyor build - invocation of coveralls.net:

    & $coveralls --opencover -i OpenCover_CoverageData.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID --serviceName AppVeyor

coveralls.net output:

    Usage:
    csmacnz.Coveralls (--opencover | --dynamiccodecoverage | --monocov) -i ./opencovertests.xml (--repoToken <repoToken> | [--repoTokenVariable <repoTokenVariable>]) [-o ./opencovertests.json] [--dryrun] [--useRelativePaths [--base Path <path>] ] [--commitId <commitId> --commitBranch <commitBranch> [--commitAuthor <commitAuthor> --commitEmail <commitEmail> --commitMessage <commitMessage>] ] [--jobId <jobId>] [--serviceName <Name>] [--treatUploadErrorsAsWarnings]
    csmacnz.Coveralls --version
    csmacnz.Coveralls --help

Since we have not changed invocation of coveralls.net (see e.g. [this build](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.6.0.407)), I'm pretty sure that the problem is not a "usage" problem.

Here's our [latest (and failing) build](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.6.0.413) and the [appveyor.yml](https://github.com/csoltenborn/GoogleTestAdapter/blob/master/appveyor.yml).

Is this a coveralls.io issue (e.g., is their web service not available at times)? Or is this even an AppVeyor issue (e.g., some env variables are not bound to their correct values, thus causing the "Usage" output of coveralls.net)? How can I debug the actual cause of the problem?

Thanks in advance!

Edited: Forgot to mention that we are using coveralls.net v0.6

**Comment by csMACnz** [comment]
Here is my initial diagnosis and suggestion:

Because you are seeing usage, it probably means one of your argument values is missing. What do i mean by this? Well lets look at your script:

    & $coveralls --opencover -i OpenCover_CoverageData.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID --serviceName AppVeyor

specifically lets take `--commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID`

(Normal problem)
if for instance `$env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL` is empty, then the string evaluates with `--commitEmail  --commitMessage` and there isn't a valid parse for an argument of `--commitEmail` and so shows usage.  This most commonly happens if, for instance `$env:COVERALLS_REPO_TOKEN` is not set.


(My guess, a wild guess by the way)
In your situation, I think it is actually your commit message `Revert "updated some nuget references"` which has quotes in it. That seems to be the pattern for your failures vs your successes?

Solution:
I probably need to have a look at how i am handling this, if it is possible to fix, otherwise for now maybe try putting single quotes around the '$env:APPVEYOR_REPO_COMMIT_MESSAGE'? I would say avoid `"` in your comments but i believe that is a GitHub thing.

Thanks for taking the time to report this :)

**Comment by csoltenborn** [comment]
And thanks for your fast answer! Your diagnosis sounds reasonable, I must admit - however, enclosing the comments in single quotes doesn't work, since the appveyor env variable appears to not be resolved any more:

![image](https://cloud.githubusercontent.com/assets/352576/15447282/fbe79394-1f3d-11e6-9f87-25bf0702437e.png)

Here's a suggestion, however, to make such issues easier to debug: how about printing all command line parameters and the values passed before showing the usage message in case argument parsing fails?

**Comment by csoltenborn** [comment]
Here's a little update: It doesn't seem to (only) be related to the quotes in the commit message. This build went through just fine (again without single quotes around the commit message variable) - Github:
![image](https://cloud.githubusercontent.com/assets/352576/15447613/c8cff270-1f48-11e6-9fd3-721abce6f00c.png)

coveralls.io:
![image](https://cloud.githubusercontent.com/assets/352576/15447620/e4b74524-1f48-11e6-96b3-610c4ac8c64c.png)

**Comment by csMACnz** [comment]
Sorry, I can't just print the values because that would expose security tokens onto your public build output, so not an option.  

Keep investigating using double quotes with other variables and you might stumble on the broken one? If you use double quotes it won't affect the $env variables (I may have been wrong about the single quotes helping I think)

**Comment by csoltenborn** [comment]
What about printing the values if parsing fails, but a certain command line option (e.g., `--debugArguments`) is set (and has to be provided as the first option)? I understand that you cannot do this in general (hadn't thought about this before), but in our case the coveralls.io security token is already public since we wanted to have code coverage also in case of pull requests (for which, again for security reasons, AppVeyor does not decrypt the secure variables)...

**Comment by csMACnz** [comment]
Yeah, seems reasonable, i'll add something like that in. I might leave it undocumented in the inbuilt help but list it on the website under troubleshooting and see how that goes.

I was trying to work out if i could pattern match out the passwords for XXXX but that would probably require me adding more argument parsing code to the mix :/ . It makes sense to add this in and leave it up to the user to be careful with it.

The library i am using for command line argument parsing [docopt.net](https://github.com/docopt/docopt.net) and for all the help it gives you to ensure you get well-formed arguments, it lacks a bit of finesse when you pass incorrect ones. I need to find some time to contribute back to it with its error handling I think.

**Comment by csoltenborn** [comment]
In fact, I think it might be a better idea to not display anything unless the user ecplicitly asks for it. It would be enough to use the password for any other option due to a copy&paste error to have a security issue...

Back to the original problem: Currently our build works fine. My plan is to add some debug code in the next days (and print the passed args on my own, at least until that coveralls.net option is in place). Shall we in the meantime close this issue? I would then open a new one as needed... otherwise, I will report here in case we have issues again.

**Comment by csMACnz** [comment]
I've had a think about this, and it seems safer for the user to decide to replicate their arguments if they want to see what is being passed in, rather than the app printing it. (I think this is the approach you have described going with anyway).

I will still look into a way to make it clearer where the missing argument is if i can.
