### ISSUE TITLE
Support multiple files

### ISSUE THREAD

**Issue by HarelM** [csMACnz/coveralls.net#59]
Consider the following scenario: a user wants to send multiple coverage files to coveralls website from a single command line run.
Feature proposal: add `--folder` flag.
This flag will receive a folder as input.
The code will take all the files in that folder and parse them according to file extensions.
file.opencover.xml (or file.opencover haven't decided yet) will be parsed as open cover
file.chuzpah.json (or file.chutzpah) will be parsed as chutzpah
file.lcov will be parsed as lcov (pending implementation of lcov format).

I'm not entirely familiar with the other options but I think that there's an option now that uses a folder which may use the same mechanism.

As a part of this changes I really think it would be wise to add an IoC container and some folders to split the logic into business logic and data access.
The current state doesn't really support unit testing well as far as I could see.

Also I think that the parsers should receive a file path and they should all inherit from the same interface.

What do you think?

**Comment by csMACnz** [comment]
The multiple coverage files needs a bit of thought. the API could do with a rewrite and that may be a good opportunity to do so to add that support, perhaps even removing the mutually exclusive requirement. I will take it under advisement. I also thought the API supported multiple posts against the same commit, so a bit of investigation is needed there, too.

As for IOC, refactoring and testability - This is a hobby project, and therefore a learning opportunity for me. I was both trying out a few techniques that I wouldn't be able to do in my day job, while also rushing to produce a proof of concept for the functionality that I actually wanted to use on other projects. As such there is no financial gain for me to spend a lot of time `yak shaving`.  I'm also not a huge fan of containers when there is already perfectly adequate IOC in the app anyway, and have found that containers promote poor and dangerous coupling because it is so 'easy' to add a dependency on something, or interfacing something that you probably shouldn't, and ending up in Mocking hell.  While I don't disagree that the app could do with some TLC, I don't have the time, and the value proposition is very very low, compared to my other focusses. Having said that, there are a few learning techniques I would like to try out and this code base could possibly be the target of that at some point soon.

Otherwise, unless someone is willing to pay me to do so, I'm not willing to do drastic refactors unless it is necessary to support new features, and I think the ability to run a new coverage file at all might be more important than wasting time on refactors. But I can see that multiple files will be necessary when you have one opencover file and one chutzpah file, one way or another.

Sorry if that is a bit rant-y.

**Comment by HarelM** [comment]
I have a few hours tonight. This project as far as I can tell is very small and I think I can contribute quite a lot in a short period of time (to judge from last night work).
I could create a project if my own but I don't think it's the right approach.
I don't want to spoil your fun with tech and stuff...

I don't agree about IOC, the fact that it's easy makes it a very robust solution, coupling as far as my experience go it mostly related to bad architecture. But I'm entitled to my opinion as you are entitled to yours.

I would like to progress with the implementation of this issue tonight nevertheless since this is the last missing piece in my CI integration.

If you have a better idea how to implement it let me know, this is the simplest solution I could think of that is related to command-line, as other solutions require the user to specify the type for each file which is not so user friendly.

Maybe another option is to use dot cover's approach:
Split the tool into basic methods:
Coverage - creates a file this tool will be able to use later
Merge - merges a few files into on file
Send - sends the file to coveralls site.

Each action can be used in command-line separately allowing the build script to run then one after the other.

Any thoughts?

**Comment by csMACnz** [comment]
I really appreciate all the attention and it is encouraging that people actually use the tool and it can be beneficial to more people with these changes. 

I don't have much time to help right now, but if your work looks good I'll at least push it through to at least an RC published to NuGet so that it isn't blocking you.

Thanks

**Comment by HarelM** [comment]
Fair enough, which of the two approaches described above sounds better to you?
using the ```--folder``` flag and depend on file extensions
or 
move to a dotcover like approach with a command (```--parse/--merge/--publish```) and different arguments per command?

I think the first approach is more compatible with the current usage but the second approach is probably more robust and scalable but breaks the current usage, I think...

Last question, Do you want me to create a separate branch for it? if so what do you think should be its name?

Thanks again for the high availability to answer my annoying questions :-)

**Comment by csMACnz** [comment]
I've had a short think and the answer is probably both and neither.

I really don't want to break backwards compatibility without doing it drastically (with a major 1.0 or 2.0 release or something). So i think longer term I will look at something like the multistep process.

In the short-term, I am worried about putting any smarts to determine the file type, or to rely on filenames to pick the provider. Especially since one of the types is a folder of files already, not a single file.

Like I said more thought is required to get this right, or a lot more work than I can focus on this week, or next.

Your best bet might be to fork it and get what you need working if you want to get something that solves your current problem, and I can look at cherry-picking back in what makes sense later on.

**Comment by HarelM** [comment]
All done.
The refactoring was in most of the classes but not a huge logic change, in the end for this small project there's not a real need for IoC as you said.
Added the folder flag for now as I don't have a better idea.
What should I do next? try to send a pull request from my master branch to your develop branch? is it possible? We use TFS at work so I'm not well experienced with git branches etc.

**Comment by csMACnz** [comment]
Should work from your master. ill have a look tomorrow. cheers.

**Comment by HarelM** [comment]
Let me know if and when you plan to create a NuGet package (even if it's targeted as pre-release) I want to test the whole cycle of my CI with it.
Enjoy! :-)

**Comment by csMACnz** [comment]
The lastest unstable from develop now supports this using --multiple -I coverage1:coverage1file;coverage2;coverage2file

This will be in the next release.

**Comment by HarelM** [comment]
I think I wrote somewhere that I have successfully tested it with my CI. Thanks!

**Comment by csMACnz** [comment]
While this has been in the 0.8.0 beta for a while, this is in the 1.0.0 release.

I may retroactively release 0.8.0 now, in case people are not ready to jump to the new .net 2.1 cli tool.
